version: "3"
services:
  app:
    image: "macnoob/devops-for-programmers-project-74"
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8080:8080"
    volumes:
      - "./app:/app"
    command: bash -c "npm test"