services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./app:/app"
    ports:
      - "8080:8080"
    command: bash -c "sleep 3 && npm start"

  caddy:
    image: caddy:2.6
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - .app/:/srv
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile