name: push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Login to DockerHub
      - uses: docker/login-action@d7365dd9cf34b10ca189f85c95c21a0c33e44092f85ffb5884d5e737fb0b9be1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ DOCKER_PASSWORD }}

      - name: Run test
        run: make test

      - name: Build image
        run: make build

      - name: Push image
        run: make push